name: Lighthouse Audit

on:
  deployment_status:

jobs:
  lighthouse:
    name: Performance Audit
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Production'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ github.event.deployment_status.target_url }}
            ${{ github.event.deployment_status.target_url }}/home
            ${{ github.event.deployment_status.target_url }}/search
          runs: 1
          temporaryPublicStorage: true
